import type { Article } from './types';

const UP = 'https://www.amsterdamnow.com/app/uploads';

// Demo-artikelen gebaseerd op echte AmsterdamNOW-content, zodat de tool zonder
// WordPress-credentials volledig te bekijken en te testen is.
export const DEMO_ARTICLES: Article[] = [
  {
    id: 86457,
    title: 'Techlab Marineterrein: robots bouwen en 3D-printen voor kids',
    subregel: 'Elke woensdag en zaterdag tijdens de zomervakantie gratis binnenlopen op het Marineterrein',
    intro:
      'Op het Marineterrein kunnen kinderen van 6 tot 12 jaar deze zomer kennismaken met techniek op hun eigen manier. Geen aanmelding, geen vast programma, gewoon binnenlopen en zelf kiezen. Robots, minicomputers, racebootjes en 3D-printers staan klaar.',
    contentHtml:
      '<h2>Op het Marineterrein, dat voormalig marinevaarterrein op Kattenburg dat de afgelopen jaren is uitgegroeid tot een plek waar technologie en creativiteit samenkomen, zit Techlab verscholen in gebouw 003G. Vier middagen per week, de hele zomervakantie lang, staat het open voor kinderen die zin hebben om iets te maken, bouwen of programmeren. Geen ticket, geen reservering, gewoon naar binnen lopen.</h2>\n<p>Begeleiders van Techlab zijn aanwezig om te helpen als kinderen vastlopen of een idee willen uitwerken. Maar het initiatief ligt bij de kinderen zelf. Geen meester voor de klas die uitlegt wat je moet doen. Wel iemand die naast je staat als je wil weten hoe een sensor werkt, of waarom je racebootje niet wil rijden.</p>\n<blockquote><p>Kinderen leren het meest als ze zelf mogen uitproberen en ontdekken wat werkt en wat niet.</p></blockquote>\n<p>Techlab is er elke woensdag en zaterdag van 8 juli tot en met 15 augustus, van 13:00 tot 17:00 uur. Ouders en verzorgers blijven in de buurt, maar verder is de drempel laag. Kattenburg en het Marineterrein zijn het verkennen waard, ook buiten Techlab om.</p>',
    status: 'draft',
    link: 'https://www.amsterdamnow.com/?p=86457',
    modified: new Date().toISOString(),
    date: new Date().toISOString(),
    category: 'Cultuur',
    district: 'Amsterdam Centrum',
    rubriek: 'Locatie',
    featured: { id: 86463, url: `${UP}/techlab_event_marineterrein_amsterdam_3-e1783018526390.jpeg` },
    inline: null,
    slider: [],
    fotograaf: 'Marineterrein Amsterdam',
    naam_locatie: 'Techlab Marineterrein',
    adres: 'Kattenburgerstraat 5, gebouw 003G',
    stad: 'Amsterdam',
    website: 'https://marineterrein.nl',
    cordA: '4.9167027',
    cordB: '52.3729682',
    tags: ['Kids', 'Attracties', 'Marineterrein'],
    focusKeyword: 'techlab marineterrein',
    slug: 'techlab-marineterrein-robots-kids',
    seoTitle: 'Techlab Marineterrein | Robots bouwen en 3D-printen',
    metaDescription:
      'Techlab in gebouw 003G op Kattenburg is een makerspace waar kinderen robots bouwen, programmeren en 3D-printen tijdens de zomervakantie.',
    flags: { new_in_town: true, featured_item: false, beste_van_amsterdam: false, homepage_carousel: false },
  },
  {
    id: 86412,
    title: 'Bols Spritz Garden: spritzes en oesters aan de Amstel',
    subregel: 'De tuin van het Amstel Hotel wordt deze zomer een Italiaanse spritz-tuin',
    intro:
      'In de tuin van het Amstel Hotel schenkt Bols deze zomer spritzes met uitzicht op de Amstel. Oesters, Italiaanse hapjes en een terras dat je eerder in Milaan verwacht dan aan de Professor Tulpplein.',
    contentHtml:
      '<h2>In de tuin van het Amstel Hotel schenkt Bols deze zomer spritzes met uitzicht op de Amstel. Oesters, Italiaanse hapjes en een terras dat je eerder in Milaan verwacht.</h2>\n<p>De Spritz Garden is een samenwerking tussen Bols en het Amstel Hotel. Aan lange tafels onder de platanen proef je de klassiekers en nieuwe combinaties met Bols-likeuren.</p>\n<blockquote><p>Een spritz aan het water, met de boten die voorbij varen: meer zomer wordt het niet in de stad.</p></blockquote>\n<p>De tuin is de hele zomer open bij goed weer. Reserveren hoeft niet, aanschuiven mag.</p>',
    status: 'draft',
    link: 'https://www.amsterdamnow.com/?p=86412',
    modified: new Date().toISOString(),
    date: new Date().toISOString(),
    category: 'Uitgaan',
    district: 'Amsterdam Centrum',
    rubriek: 'Evenement',
    featured: { id: 86414, url: `${UP}/bols-spritz-garden-event-amstel-hotel-amsterdam_1-e1783020934360.jpg` },
    inline: null,
    slider: [{ id: 86415, url: `${UP}/techlab_event_marineterrein_amsterdam_1-e1783016318571-600x413.jpeg` }],
    fotograaf: '',
    naam_locatie: 'Bols Spritz Garden',
    adres: 'Professor Tulpplein 1',
    stad: 'Amsterdam',
    website: 'https://bols.com',
    cordA: '4.9036',
    cordB: '52.3605',
    tags: ['Terras', 'Zomer', 'Amstel'],
    focusKeyword: 'bols spritz garden',
    slug: 'bols-spritz-garden-amstel-hotel',
    seoTitle: 'Bols Spritz Garden | Spritz-terras aan de Amstel',
    metaDescription: 'Bols Spritz Garden in de tuin van het Amstel Hotel serveert spritzes en oesters aan het water.',
    flags: { new_in_town: false, featured_item: false, beste_van_amsterdam: false, homepage_carousel: false },
  },
  {
    id: 86398,
    title: 'Choux: creatieve groentegerechten met natuurwijnen',
    subregel: 'Chef Merijn van Berlo maakt van groente de hoofdrol, aan de De Ruijterkade',
    intro:
      'Bij Choux draait het menu om groente, met vlees en vis in een bijrol. Chef Merijn van Berlo combineert fermentatie en Franse techniek met een kaart vol natuurwijnen.',
    contentHtml:
      '<h2>Bij Choux draait het menu om groente, met vlees en vis in een bijrol. Chef Merijn van Berlo combineert fermentatie en Franse techniek met een kaart vol natuurwijnen.</h2>\n<p>Het team achter Choux begon ooit als pop-up. Inmiddels is het een vaste waarde aan de De Ruijterkade, op loopafstand van Centraal.</p>\n<blockquote><p>Groente als hoofdrol is hier geen statement maar gewoon de lekkerste keuze.</p></blockquote>\n<p>Het interieur: beton, hout en veel licht van de kade. De wijnkaart leunt op kleine Europese makers.</p>',
    status: 'draft',
    link: 'https://www.amsterdamnow.com/?p=86398',
    modified: new Date().toISOString(),
    date: new Date().toISOString(),
    category: 'Restaurants',
    district: 'Amsterdam Centrum',
    rubriek: 'Locatie',
    featured: null,
    inline: null,
    slider: [],
    fotograaf: '',
    naam_locatie: 'Choux',
    adres: 'De Ruijterkade 128',
    stad: 'Amsterdam',
    website: 'https://choux.nl',
    cordA: '4.9041',
    cordB: '52.3771',
    tags: ['Natuurwijn', 'Groente'],
    focusKeyword: 'choux',
    slug: 'choux-groenterestaurant-natuurwijn',
    seoTitle: 'Choux | Groenterestaurant met natuurwijn bij CS',
    metaDescription: 'Choux aan de De Ruijterkade serveert creatieve groentegerechten met natuurwijnen van kleine Europese makers.',
    flags: { new_in_town: false, featured_item: false, beste_van_amsterdam: false, homepage_carousel: false },
  },
  {
    id: 86371,
    title: 'V12: rauwe Noord-charme in de Papaverhoek',
    subregel: 'Voormalige garage in de Papaverhoek is nu een buurtrestaurant met karakter',
    intro:
      'In een voormalige garage in de Papaverhoek zit V12: een buurtrestaurant waar de rauwe randjes van Noord bewaard zijn gebleven. Open keuken, lange tafels en een kaart die wekelijks wisselt.',
    contentHtml:
      '<h2>In een voormalige garage in de Papaverhoek zit V12: een buurtrestaurant waar de rauwe randjes van Noord bewaard zijn gebleven.</h2>\n<p>De naam verwijst naar het verleden van het pand. De open keuken staat waar ooit de brug stond.</p>\n<blockquote><p>De Papaverhoek verandert snel, maar bij V12 proef je nog het oude Noord.</p></blockquote>\n<p>De kaart wisselt wekelijks, met veel groente en vis van de afslag.</p>',
    status: 'draft',
    link: 'https://www.amsterdamnow.com/?p=86371',
    modified: new Date().toISOString(),
    date: new Date().toISOString(),
    category: 'Restaurants',
    district: 'Amsterdam Noord',
    rubriek: 'Locatie',
    featured: { id: 86373, url: `${UP}/v12-restaurant-papaverhoek-amsterdam_2.jpeg` },
    inline: null,
    slider: [
      { id: 86374, url: `${UP}/techlab_event_marineterrein_amsterdam_1-e1783016318571-1024x705.jpeg` },
      { id: 86375, url: `${UP}/bols-spritz-garden-event-amstel-hotel-amsterdam_1-e1783020934360.jpg` },
      { id: 86376, url: `${UP}/techlab_event_marineterrein_amsterdam_3-e1783018526390.jpeg` },
    ],
    fotograaf: 'V12',
    naam_locatie: 'V12',
    adres: 'Papaverhoek 12',
    stad: 'Amsterdam',
    website: 'https://v12.amsterdam',
    cordA: '4.9101',
    cordB: '52.3956',
    tags: ['Noord', 'Buurtrestaurant'],
    focusKeyword: 'v12 restaurant',
    slug: 'v12-restaurant-papaverhoek-noord',
    seoTitle: 'V12 | Buurtrestaurant in de Papaverhoek in Noord',
    metaDescription: 'V12 in de Papaverhoek is een buurtrestaurant in een oude garage, met open keuken en een wekelijks wisselende kaart.',
    flags: { new_in_town: false, featured_item: true, beste_van_amsterdam: false, homepage_carousel: false },
  },
  {
    id: 86340,
    title: 'Sup Sup Club: trek een sup uit de muur en stap het water op',
    subregel: 'Bij de Sup Sup Club huur je een sup zoals je een deelfiets pakt',
    intro: 'Sup huren zonder balie of wachtrij: bij de Sup Sup Club trek je een board uit de muur met een app.',
    contentHtml: '<h2>Sup huren zonder balie of wachtrij.</h2><p>Met een app trek je een board uit de muur en sta je binnen vijf minuten op het water.</p>',
    status: 'publish',
    link: 'https://www.amsterdamnow.com/lifestyle/sup-sup-club-trek-een-sup-uit-de-muur-en-stap-het-water-op/',
    modified: new Date().toISOString(),
    date: new Date().toISOString(),
    category: 'Lifestyle',
    district: 'Amsterdam Oost',
    rubriek: 'Locatie',
    featured: { id: 86341, url: `${UP}/techlab_event_marineterrein_amsterdam_1-e1783016318571-600x413.jpeg` },
    inline: null,
    slider: [
      { id: 86342, url: `${UP}/bols-spritz-garden-event-amstel-hotel-amsterdam_1-e1783020934360.jpg` },
      { id: 86343, url: `${UP}/v12-restaurant-papaverhoek-amsterdam_2.jpeg` },
    ],
    fotograaf: 'Sup Sup Club',
    naam_locatie: 'Sup Sup Club',
    adres: 'Zeeburgerdijk 1',
    stad: 'Amsterdam',
    website: 'https://supsupclub.nl',
    cordA: '4.94',
    cordB: '52.365',
    tags: ['Water', 'Sport'],
    focusKeyword: 'sup sup club',
    slug: 'sup-sup-club-sup-huren',
    seoTitle: 'Sup Sup Club | Sup huren via een app',
    metaDescription: 'Bij de Sup Sup Club trek je met een app een sup uit de muur en sta je binnen vijf minuten op het water.',
    flags: { new_in_town: false, featured_item: false, beste_van_amsterdam: false, homepage_carousel: true },
  },
  {
    id: 86322,
    title: 'Yayoi Kusama groots in het Stedelijk Museum',
    subregel: 'Overzichtstentoonstelling met de beroemde Infinity Mirror Rooms',
    intro: 'Het Stedelijk haalt Yayoi Kusama naar de stad, inclusief twee Infinity Mirror Rooms.',
    contentHtml: '<h2>Het Stedelijk haalt Yayoi Kusama naar de stad.</h2><p>Inclusief twee Infinity Mirror Rooms en vroeg werk dat zelden te zien is.</p>',
    status: 'publish',
    link: 'https://www.amsterdamnow.com/cultuur/yayoi-kusama-overzichtstentoonstelling-stedelijk-infinity-mirror/',
    modified: new Date().toISOString(),
    date: new Date().toISOString(),
    category: 'Cultuur',
    district: 'Amsterdam Zuid',
    rubriek: 'Evenement',
    featured: { id: 86323, url: `${UP}/techlab_event_marineterrein_amsterdam_3-e1783018526390.jpeg` },
    inline: null,
    slider: [
      { id: 86324, url: `${UP}/techlab_event_marineterrein_amsterdam_1-e1783016318571-1024x705.jpeg` },
      { id: 86325, url: `${UP}/bols-spritz-garden-event-amstel-hotel-amsterdam_1-e1783020934360.jpg` },
    ],
    fotograaf: 'Stedelijk Museum',
    naam_locatie: 'Stedelijk Museum',
    adres: 'Museumplein 10',
    stad: 'Amsterdam',
    website: 'https://stedelijk.nl',
    cordA: '4.8798',
    cordB: '52.358',
    tags: ['Musea', 'Tentoonstellingen'],
    focusKeyword: 'yayoi kusama stedelijk',
    slug: 'yayoi-kusama-stedelijk-museum',
    seoTitle: 'Yayoi Kusama | Overzicht in het Stedelijk Museum',
    metaDescription: 'Het Stedelijk Museum toont een groot Kusama-overzicht met twee Infinity Mirror Rooms.',
    flags: { new_in_town: false, featured_item: false, beste_van_amsterdam: true, homepage_carousel: true },
  },
];

export const DEMO_TOPICS: { title: string; status: string; error?: string; error_step?: string }[] = [
  { title: 'Bar Staal by Vooges: terras aan de Schinkel', status: 'queued' },
  { title: 'Kusukazu Uraguchi: ama-vissersvrouwen in Huis Marseille', status: 'queued' },
  { title: 'Kwaku Summer Festival: feest van cultuur in Zuidoost', status: 'queued' },
  { title: 'Theaterfestival De Parade terug in het Martin Luther Kingpark', status: 'queued' },
  { title: 'Flight Golf: high-tech golf en hospitality in Oost', status: 'queued' },
  { title: 'Strand IJburg opent strandseizoen 2026', status: 'queued' },
  { title: 'De Mark in Durgerdam: sterrenniveau aan het water', status: 'writing' },
  {
    title: 'Weekendtips Amsterdam: 24, 25 en 26 juli',
    status: 'failed',
    error: 'Research mislukt: time-out bij bronnen ophalen (Tavily: request timed out, 30s)',
    error_step: 'stap 3/7 research',
  },
];
